name: Build Master

on:
  push:
    branches:
      - 'master'
    paths: 
      - 'src/IdentityServer/**'
      - 'src/IdentityServer.Web/**'
      - '.github/workflows/master.yml'

jobs:
  build-identity:
    name: Build Identity
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore ./src/IdentityServer/IdentityServer.csproj
    - name: Build
      run: dotnet build ./src/IdentityServer/IdentityServer.csproj --configuration Release --no-restore

  build-identity-web:
    name: Build Identity Web
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore ./src/IdentityServer.Web/IdentityServer.Web.csproj
    - name: Build
      run: dotnet build ./src/IdentityServer.Web/IdentityServer.Web.csproj --configuration Release --no-restore

  functional:
    name: Api functional tests
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout branch
        uses: actions/checkout@main

      - name: Run service dependencies
        run: ./.github/scripts/functional.sh --up

      - name: Check running containers
        run: docker ps -a
      
      - name: Run functional tests
        run: ./.github/scripts/functional.sh --collection "*collection.json"     

      - name: Stop service dependencies
        run: ./.github/scripts/functional.sh --down
